var dir_892c880cf19884495b53e8cd9cea50ae =
[
    [ "tests", "dir_ff80aff8238614d55515b0277c24d215.html", "dir_ff80aff8238614d55515b0277c24d215" ],
    [ "addr.h", "addr_8h.html", "addr_8h" ],
    [ "async.cpp", "libs_2karm-sys_2async_8cpp.html", "libs_2karm-sys_2async_8cpp" ],
    [ "async.h", "karm-sys_2async_8h.html", "karm-sys_2async_8h" ],
    [ "chan.cpp", "chan_8cpp.html", "chan_8cpp" ],
    [ "chan.h", "chan_8h.html", "chan_8h" ],
    [ "context.h", "context_8h.html", "context_8h" ],
    [ "defs.h", "defs_8h.html", null ],
    [ "dir.cpp", "dir_8cpp.html", null ],
    [ "dir.h", "dir_8h.html", "dir_8h" ],
    [ "entry.h", "libs_2karm-sys_2entry_8h.html", null ],
    [ "fd.cpp", "libs_2karm-sys_2fd_8cpp.html", null ],
    [ "fd.h", "libs_2karm-sys_2fd_8h.html", "libs_2karm-sys_2fd_8h" ],
    [ "file.cpp", "file_8cpp.html", null ],
    [ "file.h", "file_8h.html", "file_8h" ],
    [ "info.cpp", "info_8cpp.html", "info_8cpp" ],
    [ "info.h", "info_8h.html", "info_8h" ],
    [ "launch.cpp", "launch_8cpp.html", "launch_8cpp" ],
    [ "launch.h", "launch_8h.html", "launch_8h" ],
    [ "lookup.cpp", "lookup_8cpp.html", "lookup_8cpp" ],
    [ "lookup.h", "lookup_8h.html", "lookup_8h" ],
    [ "mmap.h", "mmap_8h.html", "mmap_8h" ],
    [ "mutex.h", "mutex_8h.html", "mutex_8h" ],
    [ "pipe.cpp", "karm-sys_2pipe_8cpp.html", null ],
    [ "pipe.h", "pipe_8h.html", "pipe_8h" ],
    [ "proc.cpp", "proc_8cpp.html", "proc_8cpp" ],
    [ "proc.h", "proc_8h.html", "proc_8h" ],
    [ "socket.cpp", "socket_8cpp.html", null ],
    [ "socket.h", "socket_8h.html", "socket_8h" ],
    [ "stat.cpp", "stat_8cpp.html", "stat_8cpp" ],
    [ "stat.h", "stat_8h.html", "stat_8h" ],
    [ "time.h", "karm-sys_2time_8h.html", "karm-sys_2time_8h" ],
    [ "types.h", "karm-sys_2types_8h.html", "karm-sys_2types_8h" ]
];