var searchData=
[
  ['backgroundfilter_0',['BackgroundFilter',['../structKarm_1_1Ui_1_1BackgroundFilter.html',1,'Karm::Ui']]],
  ['bchunk_1',['BChunk',['../structKarm_1_1Io_1_1BChunk.html',1,'Karm::Io']]],
  ['be_2',['Be',['../structKarm_1_1Be.html',1,'Karm']]],
  ['be_3c_20u16_20_3e_3',['Be&lt; u16 &gt;',['../structKarm_1_1Be.html',1,'Karm']]],
  ['be_3c_20u32_20_3e_4',['Be&lt; u32 &gt;',['../structKarm_1_1Be.html',1,'Karm']]],
  ['bemit_5',['BEmit',['../structKarm_1_1Io_1_1BEmit.html',1,'Karm::Io']]],
  ['bfield_6',['BField',['../structKarm_1_1Io_1_1BField.html',1,'Karm::Io']]],
  ['bgra8888_7',['Bgra8888',['../structKarm_1_1Gfx_1_1Bgra8888.html',1,'Karm::Gfx']]],
  ['bidi_8',['Bidi',['../structKarm_1_1Icu_1_1Bidi.html',1,'Karm::Icu']]],
  ['bigfrac_9',['BigFrac',['../structKarm_1_1Math_1_1BigFrac.html',1,'Karm::Math']]],
  ['binaryexpr_10',['BinaryExpr',['../structKarm_1_1Math_1_1BinaryExpr.html',1,'Karm::Math']]],
  ['bitreader_11',['BitReader',['../structKarm_1_1Image_1_1Jpeg_1_1BitReader.html',1,'Karm::Image::Jpeg::BitReader'],['../structKarm_1_1Io_1_1BitReader.html',1,'Karm::Io::BitReader']]],
  ['bits_12',['Bits',['../structKarm_1_1Bits.html',1,'Karm']]],
  ['bitwriter_13',['BitWriter',['../structKarm_1_1Image_1_1Jpeg_1_1BitWriter.html',1,'Karm::Image::Jpeg']]],
  ['blob_14',['Blob',['../structKarm_1_1Kv_1_1Blob.html',1,'Karm::Kv']]],
  ['block_15',['Block',['../structKarm_1_1Text_1_1Prose_1_1Block.html',1,'Karm::Text::Prose']]],
  ['blurfilter_16',['BlurFilter',['../structKarm_1_1Gfx_1_1BlurFilter.html',1,'Karm::Gfx']]],
  ['body_17',['Body',['../structKarm_1_1Http_1_1Body.html',1,'Karm::Http']]],
  ['borders_18',['Borders',['../structKarm_1_1Gfx_1_1Borders.html',1,'Karm::Gfx']]],
  ['bound_19',['Bound',['../structKarm_1_1Ui_1_1Bound.html',1,'Karm::Ui']]],
  ['box_20',['Box',['../structKarm_1_1Box.html',1,'Karm::Box&lt; T &gt;'],['../structKarm_1_1Scene_1_1Box.html',1,'Karm::Scene::Box'],['../structKarm_1_1Ui_1_1Box.html',1,'Karm::Ui::Box']]],
  ['boxshadow_21',['BoxShadow',['../structKarm_1_1Gfx_1_1BoxShadow.html',1,'Karm::Gfx']]],
  ['boxstyle_22',['BoxStyle',['../structKarm_1_1Ui_1_1BoxStyle.html',1,'Karm::Ui']]],
  ['bpattern_23',['BPattern',['../structKarm_1_1Io_1_1BPattern.html',1,'Karm::Io']]],
  ['bpevocab_24',['BpeVocab',['../structKarm_1_1Ml_1_1BpeVocab.html',1,'Karm::Ml']]],
  ['brightnessfilter_25',['BrightnessFilter',['../structKarm_1_1Gfx_1_1BrightnessFilter.html',1,'Karm::Gfx']]],
  ['bscan_26',['BScan',['../structKarm_1_1Io_1_1BScan.html',1,'Karm::Io']]],
  ['buf_27',['Buf',['../structKarm_1_1Buf.html',1,'Karm']]],
  ['buf_3c_20u8_20_3e_28',['Buf&lt; u8 &gt;',['../structKarm_1_1Buf.html',1,'Karm']]],
  ['bufferwriter_29',['BufferWriter',['../structKarm_1_1Io_1_1BufferWriter.html',1,'Karm::Io']]],
  ['bufreader_30',['BufReader',['../structKarm_1_1Io_1_1BufReader.html',1,'Karm::Io']]],
  ['bufwriter_31',['BufWriter',['../structKarm_1_1Io_1_1BufWriter.html',1,'Karm::Io']]],
  ['builder_32',['Builder',['../structKarm_1_1Gfx_1_1Gradient_1_1Builder.html',1,'Karm::Gfx::Gradient::Builder'],['../structKarm_1_1Text_1_1FontFamily_1_1Builder.html',1,'Karm::Text::FontFamily::Builder']]],
  ['bundleinfo_33',['BundleInfo',['../structKarm_1_1Pkg_1_1BundleInfo.html',1,'Karm::Pkg']]],
  ['button_34',['Button',['../structKarm_1_1Ui_1_1Button.html',1,'Karm::Ui']]],
  ['buttonstyle_35',['ButtonStyle',['../structKarm_1_1Ui_1_1ButtonStyle.html',1,'Karm::Ui']]]
];
